export * from './Home/Home'
export * from './GenerateFiles/GenerateFiles'
export * from './WordFrequency/WordFrequency'
export * from './PaliSort/PaliSort'
export * from './Count/Count'
export * from './Converter/Converter'
export * from './InflectPage/InflectPage'
export * from './ComingSoon/ComingSoon'
